
export const redditPresets = [
    {
        name: "1",
        subreddits: ["furrygooners", "furryfuel", "cringe_porn", "ClopClop", "CringeTardGoonFuel", "FurryFemboy", "HeantaiiGooning", "GOONED", "FurryGoonPit", "GoonForBoobs", "FurryFrot", "FemboyHentai", "GoonForAss"],
        sort: "hot",
        time: "day",
        roundRobin: true,
        isPreset: true,
    },
    {
        name: "Hentai",
        subreddits: ["hentai", "freeusehentai", "hentaibreeding", "cumhentai", "rule34", "hentaianal", "hentaicumsluts", "oralhentai", "bimbohentai", "bbchentaicult"],
        sort: "hot",
        time: "day",
        roundRobin: true,
        isPreset: true,
    },
    {
        name: "Fem Cock",
        subreddits: ["futacum", "horsecockfuta", "futanari", "monsterfuta", "futaai", "femboyhentai", "sissyhentai", "femboys", "femboycum", "sissies", "shemale_big_cock", "shemales", "transporn", "shemalecumwhilefucked", "tgirlscum", "tscum", "tgirls", "tgirlsfucking", "shemalesparadise", "transdeepthroat"],
        sort: "hot",
        time: "day",
        roundRobin: true,
        isPreset: true,
    },
    {
        name: "GOON",
        subreddits: ["GOONED", "goon_caption", "goonforalice", "pornism", "tgirlgoon", "censoredforbetas", "GoonForAss", "hentai_goon", "GoonForBoobs", "GoonForPremiumAss"],
        sort: "hot",
        time: "day",
        roundRobin: true,
        isPreset: true,
    },
    {
        name: "Hypno/Conversion",
        subreddits: ["straighttosissy", "sissycaptions", "sissyinspiration", "sissyhypno", "forcedFeminization", "hypnohentai", "hypnoboobies", "hypnocaps"],
        sort: "hot",
        time: "day",
        roundRobin: true,
        isPreset: true,
    },
    {
        name: "Cock Suckers",
        subreddits: ["facefuck", "facefuckhentai", "deepthroat", "blowbang", "iwanttosuckcock", "blowjobs", "sloppyblowjob", "eliteblowjob"],
        sort: "hot",
        time: "day",
        roundRobin: true,
        isPreset: true,
    },
    {
        name: "Pussy",
        subreddits: ["Dildo_pov", "DildoRide", "dildo", "Penetration_gifs", "GodPussy", "PussyFinish", "PussyWallet", "pussy"],
        sort: "hot",
        time: "day",
        roundRobin: true,
        isPreset: true,
    },
]